#!/bin/bash

reminderPATH="$HOME/.config/$0/reminders"

if [ ! -d $reminderPATH ] ; then
	if [ ! -d "$HOME/.config/$0" ] ; then
		if [ ! -d "$HOME/.config" ] ; then
			mkdir "$HOME/.config"
			mkdir "$HOME/.config/$0"
			mkdir $reminderPATH
		else
			mkdir "$HOME/.config/$0"
			mkdir $reminderPATH
		fi			
	else
		mkdir $reminderPATH
	fi
fi

if [ $1 == "-A" ] ; then
	if [ $2 == "" ] ; then
		echo "Please specify the name for your new reminder"
	else
		touch $reminderPATH"/$2"
	fi
fi
